apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector-mcp.fullname" . }}
  labels:
    {{- include "otel-collector-mcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otel-collector-mcp.selectorLabels" . | nindent 4 }}
